### ISSUE TITLE
getting Jamf wants to access "system events " when running on 12.6.3

### ISSUE THREAD

**Issue by rondelltron** [PezzaD84/macOS-Patching-Updates#2]
<img width="372" alt="Screen Shot 2023-03-29 at 11 49 26 AM" src="https://user-images.githubusercontent.com/87993359/228619974-a72f1156-ac3a-43ea-a9a3-88bed00703c0.png">
this just started happening not sure what the issue is?

**Comment by PezzaD84** [comment]
Hi,

This is a PPPC issue. In your Jamf settings you need to set it to create a PPPC profile for Jamf when devices are enrolled.
